export interface SeedExercise {
  id?: string;
  name: string;
  targetMuscle: string;
  equipment: string;
  sets: number;
  reps: string;
  restSeconds: number;
  instructions: string[];
  formCues: string[];
  thumbnail: string;
}

export interface SeedWorkout {
  id: string;
  customId?: string;
  title: string;
  category: "strength" | "hiit" | "cardio" | "mobility" | "power";
  targetGoal: "hypertrophy" | "fat_loss" | "endurance" | "strength";
  duration: number;
  calories: number;
  difficulty: "beginner" | "intermediate" | "advanced";
  equipment: "bodyweight" | "dumbbell" | "barbell" | "cables" | "kettlebell";
  bodyPart: "full_body" | "chest" | "back" | "legs" | "core" | "arms";
  exercisesCount: number;
  description: string;
  thumbnail: string;
  videoUrl?: string;
  exercises: SeedExercise[];
  createdAt?: string;
  updatedAt?: string;
}

export const initialSeedWorkouts: SeedWorkout[] = [
  {
    id: "w-1",
    customId: "w-1",
    title: "Full Body HIIT Ignition",
    category: "hiit",
    targetGoal: "fat_loss",
    duration: 25,
    calories: 340,
    difficulty: "intermediate",
    equipment: "dumbbell",
    bodyPart: "full_body",
    exercisesCount: 3,
    description: "High-density metabolic conditioning circuit designed to maximize post-exercise oxygen consumption (EPOC).",
    thumbnail: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800",
    exercises: [
      {
        id: "ex-1-1",
        name: "Dumbbell Thrusters",
        targetMuscle: "Full Body & Delts",
        equipment: "Dumbbells",
        sets: 4,
        reps: "12 reps",
        restSeconds: 45,
        instructions: [
          "Hold dumbbells at shoulder height in a neutral rack position.",
          "Squat to parallel with chest proud and knees tracking outward.",
          "Explosively drive through the heels and press weights overhead in one fluid motion.",
        ],
        formCues: ["Keep core braced at bottom", "Lock out elbows overhead", "Inhale on descent"],
        thumbnail: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-1-2",
        name: "Kettlebell Russian Swings",
        targetMuscle: "Posterior Chain & Glutes",
        equipment: "Kettlebell",
        sets: 4,
        reps: "15 reps",
        restSeconds: 45,
        instructions: [
          "Hinge at hips with soft knees, grasping kettlebell with both hands.",
          "Drive hips forward powerfully, snapping glutes to propel bell to eye level.",
          "Control the pendulum arc back through legs without squatting.",
        ],
        formCues: ["Hinge, don't squat", "Glutes locked at peak", "Spine neutral throughout"],
        thumbnail: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-1-3",
        name: "Renegade Rows & Pushup",
        targetMuscle: "Core & Lats",
        equipment: "Dumbbells",
        sets: 3,
        reps: "10 reps / side",
        restSeconds: 45,
        instructions: [
          "Set up in a tall plank position holding two hex dumbbells.",
          "Perform a strict pushup with chest brushing dumbbells.",
          "Row right dumbbell to hip without rotating hips, repeat on left.",
        ],
        formCues: ["Keep hips square to floor", "Squeeze core to eliminate sway", "Full depth pushup"],
        thumbnail: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&q=80&w=600",
      },
    ],
  },
  {
    id: "w-2",
    customId: "w-2",
    title: "Hypertrophy Chest & Back",
    category: "strength",
    targetGoal: "hypertrophy",
    duration: 45,
    calories: 420,
    difficulty: "advanced",
    equipment: "barbell",
    bodyPart: "chest",
    exercisesCount: 4,
    description: "Antagonistic agonist upper body volume split focusing on deep stretch positions and mechanical tension.",
    thumbnail: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800",
    exercises: [
      {
        id: "ex-2-1",
        name: "Incline Barbell Bench Press",
        targetMuscle: "Clavicular Pectoralis & Triceps",
        equipment: "Barbell",
        sets: 4,
        reps: "8-10 reps",
        restSeconds: 90,
        instructions: [
          "Set incline bench to 30 degrees to bias upper chest fibers.",
          "Retract and depress scapula firmly into the pad.",
          "Lower bar with control to upper chest, then drive up without shrugging shoulders.",
        ],
        formCues: ["Elbows tucked 45-60 degrees", "Touch upper chest lightly", "Maintain leg drive"],
        thumbnail: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-2-2",
        name: "Bent-Over Barbell Row",
        targetMuscle: "Latissimus Dorsi & Rhomboids",
        equipment: "Barbell",
        sets: 4,
        reps: "8-10 reps",
        restSeconds: 90,
        instructions: [
          "Hinge torso forward to ~45 degrees with knees slightly bent and spine rigid.",
          "Grip barbell slightly wider than shoulder width.",
          "Pull barbell toward lower ribcage, driving elbows past the torso and squeezing scapulae.",
        ],
        formCues: ["Do not use hip bounce", "Pull with elbows, not biceps", "Hold peak contraction 1s"],
        thumbnail: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-2-3",
        name: "Flat Dumbbell Fly & Press Hybrid",
        targetMuscle: "Sternal Pectoralis",
        equipment: "Dumbbells",
        sets: 3,
        reps: "10-12 reps",
        restSeconds: 60,
        instructions: [
          "Lie flat with dumbbells extended above chest in a neutral grip.",
          "Lower in a wide arc with slight elbow bend until a deep stretch is achieved across pectorals.",
          "Drive back together along the same arc, contracting chest at the apex.",
        ],
        formCues: ["Emphasize the 3-second eccentric stretch", "Do not hyperextend shoulders", "Keep chest expanded"],
        thumbnail: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-2-4",
        name: "Neutral Grip Lat Pulldown",
        targetMuscle: "Lats & Lower Traps",
        equipment: "Cables",
        sets: 3,
        reps: "10-12 reps",
        restSeconds: 60,
        instructions: [
          "Attach neutral grip handle and sit securely with thigh pads locked.",
          "Lean back slightly (~10 degrees) and pull bar down toward upper sternum.",
          "Slowly release under tension to full overhead lat stretch.",
        ],
        formCues: ["Lead with elbows", "Avoid leaning excessively backwards", "Full stretch at top"],
        thumbnail: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&q=80&w=600",
      },
    ],
  },
  {
    id: "w-3",
    customId: "w-3",
    title: "Core Power & Hip Mobility",
    category: "mobility",
    targetGoal: "endurance",
    duration: 20,
    calories: 180,
    difficulty: "beginner",
    equipment: "bodyweight",
    bodyPart: "core",
    exercisesCount: 3,
    description: "Dynamic pelvis alignment, thoracic rotation, and rotational core stability drills for injury resilience.",
    thumbnail: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=800",
    exercises: [
      {
        id: "ex-3-1",
        name: "Dead Bug Core Stabilization",
        targetMuscle: "Transverse Abdominis",
        equipment: "Bodyweight",
        sets: 3,
        reps: "12 reps / side",
        restSeconds: 45,
        instructions: [
          "Lie on back with arms extended upward and hips/knees flexed at 90 degrees.",
          "Press lower back flush against the ground.",
          "Slowly extend opposite arm and leg toward floor without arching spine.",
        ],
        formCues: ["Never let lower back arch", "Move slowly under control"],
        thumbnail: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-3-2",
        name: "World's Greatest Stretch & Thoracic Opener",
        targetMuscle: "Hips, Glutes & T-Spine",
        equipment: "Bodyweight",
        sets: 3,
        reps: "8 reps / side",
        restSeconds: 45,
        instructions: [
          "Step into a deep forward lunge with hands inside front foot.",
          "Drop inside elbow toward ankle, then rotate chest and hand toward ceiling.",
          "Shift weight back to stretch front hamstring.",
        ],
        formCues: ["Breathe into the hip opener", "Follow hand with gaze"],
        thumbnail: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-3-3",
        name: "Paloff Press Isometric Hold",
        targetMuscle: "Anti-Rotation Core",
        equipment: "Cables or Band",
        sets: 3,
        reps: "30s hold / side",
        restSeconds: 45,
        instructions: [
          "Stand perpendicular to cable anchor holding handle at sternum.",
          "Press handle straight out in front and resist rotational torque.",
        ],
        formCues: ["Maintain square hips and shoulders", "Breathe steadily"],
        thumbnail: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=600",
      },
    ],
  },
  {
    id: "w-4",
    customId: "w-4",
    title: "Quads & Hamstrings Annihilation",
    category: "strength",
    targetGoal: "hypertrophy",
    duration: 50,
    calories: 480,
    difficulty: "advanced",
    equipment: "barbell",
    bodyPart: "legs",
    exercisesCount: 3,
    description: "Heavy squat compounds followed by Romanian deadlifts and unilateral Bulgarian split squats.",
    thumbnail: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&q=80&w=800",
    exercises: [
      {
        id: "ex-4-1",
        name: "Barbell Back Squat",
        targetMuscle: "Quadriceps & Gluteus Maximus",
        equipment: "Barbell",
        sets: 4,
        reps: "6-8 reps",
        restSeconds: 120,
        instructions: [
          "Position barbell across upper traps with elbows pulled tight.",
          "Break at hips and knees simultaneously, descending until thighs are at or below parallel.",
          "Drive straight up pushing floor away through midfoot.",
        ],
        formCues: ["Chest upright", "Knees in line with toes", "Brace with Valsalva maneuver"],
        thumbnail: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-4-2",
        name: "Romanian Deadlift (RDL)",
        targetMuscle: "Hamstrings & Glute-Ham Tie-in",
        equipment: "Barbell",
        sets: 4,
        reps: "8-10 reps",
        restSeconds: 90,
        instructions: [
          "Stand tall holding barbell at hip width.",
          "Hinge hips backward with soft knees, gliding bar down along shins.",
          "Drive hips forward to return to standing lockout.",
        ],
        formCues: ["Feel deep hamstring stretch", "Do not round lower back", "Bar stays in contact with legs"],
        thumbnail: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-4-3",
        name: "Bulgarian Split Squat",
        targetMuscle: "Quads & Glute Medius",
        equipment: "Dumbbells",
        sets: 3,
        reps: "10 reps / leg",
        restSeconds: 60,
        instructions: [
          "Rest rear foot on bench behind you holding dumbbells.",
          "Lower until front thigh is parallel, keeping knee stacked over ankle.",
          "Drive through front heel to return to top.",
        ],
        formCues: ["Keep torso slight forward lean", "Control the descent"],
        thumbnail: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&q=80&w=600",
      },
    ],
  },
  {
    id: "w-5",
    customId: "w-5",
    title: "Tabata Sprint & Calisthenics",
    category: "hiit",
    targetGoal: "fat_loss",
    duration: 18,
    calories: 260,
    difficulty: "beginner",
    equipment: "bodyweight",
    bodyPart: "full_body",
    exercisesCount: 3,
    description: "20s max effort, 10s rest intervals using plyometric pushups, burpees, and mountain climbers.",
    thumbnail: "https://images.unsplash.com/photo-1434682881908-b43d0467b798?auto=format&fit=crop&q=80&w=800",
    exercises: [
      {
        id: "ex-5-1",
        name: "Chest-to-Floor Burpees",
        targetMuscle: "Full Body & Cardio",
        equipment: "Bodyweight",
        sets: 4,
        reps: "20s max reps",
        restSeconds: 10,
        instructions: [
          "Drop into squat, kick feet back, drop chest to floor.",
          "Snap feet back to hands and jump explosively overhead.",
        ],
        formCues: ["Fast transitions", "Soft landings"],
        thumbnail: "https://images.unsplash.com/photo-1434682881908-b43d0467b798?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-5-2",
        name: "Cross-Body Mountain Climbers",
        targetMuscle: "Core & Heart Rate",
        equipment: "Bodyweight",
        sets: 4,
        reps: "20s max reps",
        restSeconds: 10,
        instructions: [
          "In plank position, drive knee across body toward opposite elbow rapidly.",
        ],
        formCues: ["Flat back", "Drive knees rhythmically"],
        thumbnail: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-5-3",
        name: "Air Squats with Jump Finish",
        targetMuscle: "Quads & Calves",
        equipment: "Bodyweight",
        sets: 4,
        reps: "20s max reps",
        restSeconds: 10,
        instructions: [
          "Squat to parallel, then explode off the balls of feet into small vertical jump.",
        ],
        formCues: ["Full hip extension at top"],
        thumbnail: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=600",
      },
    ],
  },
  {
    id: "w-6",
    customId: "w-6",
    title: "Shoulder Boulders & Arms Blast",
    category: "strength",
    targetGoal: "hypertrophy",
    duration: 35,
    calories: 310,
    difficulty: "intermediate",
    equipment: "dumbbell",
    bodyPart: "arms",
    exercisesCount: 3,
    description: "Overhead press pyramid followed by lateral raise giant-sets and supersetted bicep-tricep burnout.",
    thumbnail: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&q=80&w=800",
    exercises: [
      {
        id: "ex-6-1",
        name: "Seated Dumbbell Shoulder Press",
        targetMuscle: "Anterior & Lateral Deltoids",
        equipment: "Dumbbells",
        sets: 4,
        reps: "8-10 reps",
        restSeconds: 75,
        instructions: [
          "Sit on high incline/upright bench with dumbbells at ear level.",
          "Press dumbbells overhead until bells nearly touch, lower with 2-second eccentric.",
        ],
        formCues: ["Do not arch lower back off bench", "Press straight up"],
        thumbnail: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-6-2",
        name: "Lean-Away Dumbbell Lateral Raises",
        targetMuscle: "Lateral Deltoid",
        equipment: "Dumbbells",
        sets: 4,
        reps: "12-15 reps",
        restSeconds: 60,
        instructions: [
          "Hold upright post with one hand, leaning outward slightly.",
          "Raise dumbbell laterally with pinky slightly elevated up to shoulder height.",
        ],
        formCues: ["Lead with elbows", "Avoid swinging torso"],
        thumbnail: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-6-3",
        name: "Incline Bicep Curl & Tricep Overhead Extension",
        targetMuscle: "Biceps Long Head & Triceps Long Head",
        equipment: "Dumbbells",
        sets: 3,
        reps: "12 reps each",
        restSeconds: 60,
        instructions: [
          "Superset: Curl dumbbells from deep bicep stretch on 45-deg incline bench.",
          "Immediately follow with overhead two-hand dumbbell tricep extension.",
        ],
        formCues: ["Maintain full stretch at bottom of curl", "Keep elbows pointing up on extensions"],
        thumbnail: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&q=80&w=600",
      },
    ],
  },
  {
    id: "w-7",
    customId: "w-7",
    title: "Kettlebell Ballistic Power",
    category: "power",
    targetGoal: "strength",
    duration: 30,
    calories: 350,
    difficulty: "intermediate",
    equipment: "kettlebell",
    bodyPart: "full_body",
    exercisesCount: 2,
    description: "Explosive kettlebell cleans, snatches, and Turkish get-ups to train triple extension and grip stamina.",
    thumbnail: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&q=80&w=800",
    exercises: [
      {
        id: "ex-7-1",
        name: "Single-Arm Kettlebell Clean & Push Press",
        targetMuscle: "Hips, Back, Shoulders",
        equipment: "Kettlebell",
        sets: 4,
        reps: "8 reps / side",
        restSeconds: 60,
        instructions: [
          "Hinge and clean bell into rack position at chest.",
          "Dip knees slightly and drive through legs to push press overhead.",
        ],
        formCues: ["Keep bell close to body line", "Absorbed softly in rack"],
        thumbnail: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-7-2",
        name: "Turkish Get-Up",
        targetMuscle: "Shoulder Stability & Core",
        equipment: "Kettlebell",
        sets: 3,
        reps: "3 reps / side",
        restSeconds: 60,
        instructions: [
          "Lie on back with bell locked out overhead.",
          "Follow step-by-step rolling onto elbow, hand, sweeping leg to lunge, and standing.",
        ],
        formCues: ["Eye on the bell at all times", "Arm remains completely vertical"],
        thumbnail: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=600",
      },
    ],
  },
  {
    id: "w-8",
    customId: "w-8",
    title: "Zone 2 Aerobic Base Builder",
    category: "cardio",
    targetGoal: "endurance",
    duration: 40,
    calories: 360,
    difficulty: "beginner",
    equipment: "bodyweight",
    bodyPart: "full_body",
    exercisesCount: 2,
    description: "Steady-state aerobic base conditioning to boost mitochondrial density and cardiovascular recovery.",
    thumbnail: "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&q=80&w=800",
    exercises: [
      {
        id: "ex-8-1",
        name: "Rhythmic Shadow Boxing & Footwork",
        targetMuscle: "Shoulders, Calves & Aerobic Base",
        equipment: "Bodyweight",
        sets: 4,
        reps: "5 min round",
        restSeconds: 60,
        instructions: [
          "Maintain conversational pace rhythmically throwing jab-cross-slip combinations.",
          "Keep light on the toes and stay within 65-75% maximum heart rate.",
        ],
        formCues: ["Hands up guarding chin", "Relaxed breathing through nose"],
        thumbnail: "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-8-2",
        name: "Low-Impact Calisthenics Circuit",
        targetMuscle: "Full Body Aerobic Conditioning",
        equipment: "Bodyweight",
        sets: 4,
        reps: "5 min round",
        restSeconds: 60,
        instructions: [
          "Cycle through marching high-knees, step-jacks, and torso twists steadily.",
        ],
        formCues: ["Stay in target heart rate zone 2", "Constant fluid movement"],
        thumbnail: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&q=80&w=600",
      },
    ],
  },
  {
    id: "w-9",
    customId: "w-9",
    title: "Cable Crossover & Fly Sculpt",
    category: "strength",
    targetGoal: "hypertrophy",
    duration: 30,
    calories: 270,
    difficulty: "intermediate",
    equipment: "cables",
    bodyPart: "chest",
    exercisesCount: 2,
    description: "Continuous tension cable fly angles targeting clavicular, sternal, and abdominal pectoral fibers.",
    thumbnail: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&q=80&w=800",
    exercises: [
      {
        id: "ex-9-1",
        name: "High-to-Low Cable Fly",
        targetMuscle: "Lower Pectoralis Sternal Head",
        equipment: "Cables",
        sets: 4,
        reps: "12-15 reps",
        restSeconds: 60,
        instructions: [
          "Set pulleys high above shoulder height, step forward in staggered stance.",
          "Sweep hands downward and together in a hugging motion.",
        ],
        formCues: ["Chest puffed out", "Squeeze for 1 full second at bottom"],
        thumbnail: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&q=80&w=600",
      },
      {
        id: "ex-9-2",
        name: "Low-to-High Cable Crossover",
        targetMuscle: "Clavicular Upper Chest",
        equipment: "Cables",
        sets: 3,
        reps: "12-15 reps",
        restSeconds: 60,
        instructions: [
          "Set pulleys at floor level.",
          "Drive hands upward and forward meeting at eye level with palms facing upward.",
        ],
        formCues: ["Avoid shrugging shoulders", "Feel contraction in upper clavicular fibers"],
        thumbnail: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&q=80&w=600",
      },
    ],
  },
];
