export const ROUTES = {
  HOME: "/",
  DASHBOARD: "/dashboard",
  WORKOUTS: "/workouts",
  WORKOUT_DETAIL: "/workouts/:id",
  VIDEOS: "/videos",
  COACH: "/coach",
  NUTRITION: "/nutrition",
  PROGRESS: "/progress",
  CALENDAR: "/calendar",
  PLANNER: "/planner",
  HABITS: "/habits",
  MINDFULNESS: "/mindfulness",
  HEALTH: "/health",
  ACHIEVEMENTS: "/achievements",
  FORM_CHECK: "/form-check",
  SOCIAL: "/social",
  PROFILE: "/profile",
  SETTINGS: "/settings",
} as const;
